Club 27/Controllers/BookingsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Club_27.Models;
using Microsoft.Extensions.Logging;
using Club_27.Services;

namespace Club_27.Controllers
{
    public class BookingsController : Controller
    {
        private readonly ILogger<BookingsController> _logger;
        private readonly BookingSL _bookingSL;
        private readonly ActivityMasterSL _activityMasterSL;
        private readonly VenueSL _venueSL;
        private readonly TeamSL _teamSL;

        public BookingsController(ILogger<BookingsController> logger, ActivityMasterSL activityMasterSL, TeamSL teamSL, VenueSL venueSL, BookingSL bookingSL)
        {
            _activityMasterSL = activityMasterSL;
            _venueSL = venueSL;
            _bookingSL = bookingSL;
            _teamSL = teamSL;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into HomeController");
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            return View(_bookingSL.AllBooking().ToList());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var obj = _bookingSL.GetBooking(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();

            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;

            return View();
        }

        // POST: Bookings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Booking booking)
        {
            booking.Fixture = String.Join(" vs ", booking.ParticipantList);
            var result = _bookingSL.CreateBooking(booking);
            if (result == "Success")
            {
                
                return RedirectToAction("Index");
            }
            else
                ViewBag.Error = result;

            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();

            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;


            return View(booking);            
        }

        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }
                
        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _bookingSL.GetBooking(id);

            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();


            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;
            return View(obj);
        }

        // POST: Bookings/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Booking booking)
        {
                       
            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();

            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;

            booking.Fixture = String.Join(" vs ", booking.ParticipantList);
            var result = _bookingSL.UpdateBooking(id, booking);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Duplicate Booking")
                ViewBag.Error = result;
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var obj = _bookingSL.GetBooking(id);
            return View(obj);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _bookingSL.DeleteBooking(_bookingSL.GetBooking(id));
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<JsonResult> GetVenueList(int id)
        {
            var venueList = _venueSL.AllVenue().Where(x => x.ActivityID == id).ToList();
            var venueDropDownItems = venueList.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.VenueName }).ToList();
            //var returnValue = Json(teamDropDownItems);
            return Json(venueDropDownItems);
        }

        [HttpPost]
        public async Task<JsonResult> GetTeamList(int id)
        {
            var teamList = _teamSL.AllTeam().Where(x => x.ActivityID == id).ToList();
            //var empList = _enrollmentSL.AllEnrollments.Where
            var teamDropDownItems = teamList.Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();
            //var returnValue = Json(teamDropDownItems);
            return Json(teamDropDownItems);
        }
    }
}

Club 27/Controllers/TeamsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Club_27.Models;
using Microsoft.Extensions.Logging;
using Club_27.Services;


namespace Club_27.Controllers
{
    public class TeamsController : Controller
    {

        private readonly ILogger<TeamsController> _logger;
        private readonly TeamSL _teamSL;
        private readonly ActivityMasterSL _activityMasterSL;

        public TeamsController(ILogger<TeamsController> logger, TeamSL teamSL, ActivityMasterSL activityMasterSL)
        {
            _teamSL = teamSL;
            _activityMasterSL = activityMasterSL;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into HomeController");
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            return View(_teamSL.AllTeam().ToList());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var obj = _teamSL.GetTeam(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // GET: EmployeeActivities/Create
        public IActionResult Create()
        {
            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View();
        }

        // POST: Teams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Team team)
        {
            var result = _teamSL.CreateTeam(team);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Team already exists for this activity")
                ViewBag.DuplicateError = result;

            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View(team);
        }

        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _teamSL.GetTeam(id);

            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }

        // POST: Teams/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Team team)
        {
            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            
            var result = _teamSL.UpdateTeam(id, team);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Team already exists for this activity")
                ViewBag.DuplicateError = result;
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var obj = _teamSL.GetTeam(id);
            return View(obj);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _teamSL.DeleteTeam(_teamSL.GetTeam(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

Club 27/Controllers/VenuesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Club_27.Models;
using Microsoft.Extensions.Logging;
using Club_27.Services;

namespace Club_27.Controllers
{
    public class VenuesController : Controller
    {
        private readonly ILogger<VenuesController> _logger;
        private readonly VenueSL _venueSL;
        private readonly ActivityMasterSL _activityMasterSL;

        public VenuesController(ILogger<VenuesController> logger, VenueSL venueSL, ActivityMasterSL activityMasterSL)
        {
            _venueSL = venueSL;
            _activityMasterSL = activityMasterSL;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into HomeController");
        }

        // GET: Venues
        public async Task<IActionResult> Index()
        {
            return View(_venueSL.AllVenue().ToList());
        }

        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var obj = _venueSL.GetVenue(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // GET: Venues/Create
        public IActionResult Create()
        {
            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View();
        }

        // POST: Venues/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Venue venue)
        {
            var result = _venueSL.CreateVenue(venue);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Venue already exists")
                ViewBag.Error = result;

            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View(venue);
        }

        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }

        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _venueSL.GetVenue(id);

            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }

        // POST: Venues/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Venue venue)
        {
            var TypeDropDown = _activityMasterSL.AllActivity().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            var result = _venueSL.UpdateVenue(id, venue);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Venue already exists")
                ViewBag.Error = result;
            return View(venue);
        }

        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var obj = _venueSL.GetVenue(id);
            return View(obj);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _venueSL.DeleteVenue(_venueSL.GetVenue(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

Club 27/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="Index" asp-controller="Home">
    Click here to navigate to home page
</a>

Club 27/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Club_27</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Club_27.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/select2.min.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>


    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>*@
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Club_27</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>*@

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="EmployeeMasters" asp-action="Index">Employee</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ActivityMasters" asp-action="Index">Activity</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Enrollments" asp-action="Index">Enrollment</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Teams" asp-action="Index">Team</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Venues" asp-action="Index">Venue</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Bookings" asp-action="Index">Booking</a>
      </li>
      }
                    </ul>
                    <partial name ="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Club 27 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/select2.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>