Club 27/Models/Booking.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Club_27.Models
{
    public class Booking
    {
        [Key]
        public int ID { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public int VenueID { get; set; }
        
        [ForeignKey ("VenueID")]
        public virtual Venue Venue { get; set; }

        public int ActivityID { get; set; }

        [ForeignKey ("ActivityID")]
        public virtual ActivityMaster Activity { get; set; }
        public string Fixture { get; set; }

        [NotMapped]
        public string[] ParticipantList { get; set; }
        
    }
}

Club 27/Controllers/API/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Club_27.Models;
using Club_27.Services;

namespace Club_27.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class BookingsController : ControllerBase
    {
        private readonly BookingSL bookingSL;

        public BookingsController(BookingSL booking)
        {
            bookingSL = booking;
        }

        // GET: api/Bookings
        [HttpGet]
        public ActionResult<IList<Booking>> GetBookings()
        {
            return bookingSL.AllBooking().ToList();
        }

        // GET: api/Bookings/5
        [HttpGet("{id}")]
        public ActionResult<Booking> GetBooking(int id)
        {
            var booking = bookingSL.GetBooking(id);

            if (booking == null)
            {
                return NotFound();
            }

            return booking;
        }

        // PUT: api/Bookings/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public ActionResult PutBooking(int id, Booking booking)
        {
            if (id != booking.ID)
            {
                return BadRequest();
            }
            else
            {
                if (bookingSL.UpdateBooking(id, booking) == "Success")
                    return Ok();
                else
                    return BadRequest();
            }
        }

        // POST: api/Bookings
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public ActionResult<Booking> PostBooking(Booking booking)
        {
            var result = bookingSL.CreateBooking(booking);
            if (result == "Success")
                return Ok(booking);
            else
                return BadRequest();
        }

        // DELETE: api/Bookings/5
        [HttpDelete("{id}")]
        public ActionResult DeleteBooking(int id)
        {
            var booking = bookingSL.GetBooking(id);
            if (booking == null)
            {
                return NotFound();
            }
            else
            {
                bookingSL.DeleteBooking(booking);
                return Ok();
            }
        }
    }
}

Club 27/Controllers/BookingsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Club_27.Models;
using Microsoft.Extensions.Logging;
using Club_27.Services;

namespace Club_27.Controllers
{
    public class BookingsController : Controller
    {
        private readonly ILogger<BookingsController> _logger;
        private readonly BookingSL _bookingSL;
        private readonly ActivityMasterSL _activityMasterSL;
        private readonly VenueSL _venueSL;
        private readonly TeamSL _teamSL;

        public BookingsController(ILogger<BookingsController> logger, ActivityMasterSL activityMasterSL, TeamSL teamSL, VenueSL venueSL, BookingSL bookingSL)
        {
            _activityMasterSL = activityMasterSL;
            _venueSL = venueSL;
            _bookingSL = bookingSL;
            _teamSL = teamSL;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into HomeController");
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            return View(_bookingSL.AllBooking().ToList());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var obj = _bookingSL.GetBooking(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();

            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;

            return View();
        }

        // POST: Bookings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Booking booking)
        {
            booking.Fixture = String.Join(" vs ", booking.ParticipantList);
            var result = _bookingSL.CreateBooking(booking);
            if (result == "Success")
            {
                
                return RedirectToAction("Index");
            }
            else
                ViewBag.Error = result;

            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();

            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;


            return View(booking);            
        }

        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }
                
        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _bookingSL.GetBooking(id);

            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();


            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;
            return View(obj);
        }

        // POST: Bookings/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Booking booking)
        {
                       
            var venueDropDown = _venueSL.AllVenue().ToList();
            var activityDropDown = _activityMasterSL.AllActivity().ToList();
            var teamDropDown = _teamSL.AllTeam().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();

            ViewBag.venueDropDown = venueDropDown;
            ViewBag.activityDropDown = activityDropDown;
            ViewBag.teamDropDown = teamDropDown;

            booking.Fixture = String.Join(" vs ", booking.ParticipantList);
            var result = _bookingSL.UpdateBooking(id, booking);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Duplicate Booking")
                ViewBag.Error = result;
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var obj = _bookingSL.GetBooking(id);
            return View(obj);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _bookingSL.DeleteBooking(_bookingSL.GetBooking(id));
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<JsonResult> GetVenueList(int id)
        {
            var venueList = _venueSL.AllVenue().Where(x => x.ActivityID == id).ToList();
            var venueDropDownItems = venueList.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.VenueName }).ToList();
            //var returnValue = Json(teamDropDownItems);
            return Json(venueDropDownItems);
        }

        [HttpPost]
        public async Task<JsonResult> GetTeamList(int id)
        {
            var teamList = _teamSL.AllTeam().Where(x => x.ActivityID == id).ToList();
            //var empList = _enrollmentSL.AllEnrollments.Where
            var teamDropDownItems = teamList.Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();
            //var returnValue = Json(teamDropDownItems);
            return Json(teamDropDownItems);
        }
    }
}

Club 27/Controllers/EnrollmentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Club_27.Models;
using Microsoft.Extensions.Logging;
using Club_27.Services;
using Microsoft.AspNetCore.Authorization;
using Club_27.Authorization;

namespace Club_27.Controllers
{
    [Authorize]
    public class EnrollmentsController : Controller
    {
        private readonly Club27DBContext _context;

        private readonly ILogger<EnrollmentsController> _logger;
        private readonly EnrollmentSL _enrollmentSL;
        private readonly ActivityMasterSL _activityMasterSL;
        private readonly EmployeeMasterSL _employeeMasterSL;
        private readonly TeamSL _teamSL;

        public EnrollmentsController(Club27DBContext context, ILogger<EnrollmentsController> logger, EnrollmentSL enrollmentSL, EmployeeMasterSL employeeMasterSL, TeamSL teamSL, ActivityMasterSL activityMasterSL)
        {
            _context = context;
            _enrollmentSL = enrollmentSL;
            _activityMasterSL = activityMasterSL;
            _employeeMasterSL = employeeMasterSL;
            _teamSL = teamSL;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into HomeController");
        }

        // GET: EmployeeActivities
        public async Task<IActionResult> Index()
        {
            return View(_enrollmentSL.AllEnrollment().ToList());
        }

        // GET: EmployeeActivities/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            var obj = _enrollmentSL.GetEnrollment(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // GET: EmployeeActivities/Create
        //[WebAuthorize (RolesList=new[] {Roles.Admin})]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var TypeDropDown1 = _employeeMasterSL.AllEmployee().ToList();
            var TypeDropDown2 = _activityMasterSL.AllActivity().ToList();
            var TypeDropDown3 = _teamSL.AllTeam().ToList();

            ViewBag.TypeDropDown1 = TypeDropDown1;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;

            //TempData["tempData1"] = TypeDropDown1;
            //TempData["tempCheck"] = "Check Data";
            //TempData["tempData2"] = TypeDropDown2;
            return View();
        }

        // POST: EmployeeActivities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Enrollment employeeActivity)
        {

            var result = _enrollmentSL.CreateEnrollment(employeeActivity);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Duplicate Enrollment")
                ViewBag.Error = result;
            else if (result == "Error - Maximum of 4 activities only")
                ViewBag.Error = result;
            else if (result == "Error - Team already full")
                ViewBag.Error = result;

            var TypeDropDown1 = _employeeMasterSL.AllEmployee().ToList();
            var TypeDropDown2 = _activityMasterSL.AllActivity().ToList();
            var TypeDropDown3 = _teamSL.AllTeam().ToList();

            ViewBag.TypeDropDown1 = TypeDropDown1;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;

            return View(employeeActivity);
        }

        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }

       

        // GET: EmployeeActivities/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {

            
            var obj = _enrollmentSL.GetEnrollment(id);

            var TypeDropDown1 = _employeeMasterSL.AllEmployee().ToList();
            var TypeDropDown2 = _activityMasterSL.AllActivity().ToList();
            var TypeDropDown3 = _teamSL.AllTeam().ToList();

            ViewBag.TypeDropDown1 = TypeDropDown1;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;
            return View(obj);
        }

        // POST: EmployeeActivities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id , Enrollment employeeActivity)
        {
            
            var TypeDropDown1 = _employeeMasterSL.AllEmployee().ToList();
            var TypeDropDown2 = _activityMasterSL.AllActivity().ToList();
            var TypeDropDown3 = _teamSL.AllTeam().ToList();

            ViewBag.TypeDropDown1 = TypeDropDown1;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;

            
            var result = _enrollmentSL.UpdateEnrollment(id , employeeActivity);
            if (result == "Success")
                return RedirectToAction("Index");
            else if (result == "Error - Duplicate Enrollment")
                ViewBag.Error = result;
            else if (result == "Error - Team already full")
                ViewBag.Error = result;
            return View(employeeActivity);
        }

        // GET: EmployeeActivities/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            

            var obj = _enrollmentSL.GetEnrollment(id);
            return View(obj);
        }

        // POST: EmployeeActivities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var result = _enrollmentSL.DeleteEnrollment(_enrollmentSL.GetEnrollment(id));
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(int id)
        {
            return _context.Enrollments.Any(e => e.EnrollmentID == id);
        }

        [HttpPost]
        public async Task<JsonResult> GetTeamList(int id)
        {
            var teamList = _teamSL.AllTeam().Where(x => x.ActivityID == id).ToList();
            var teamDropDownItems = teamList.Select(x => new SelectListItem { Value = x.ID.ToString() , Text = x.Name }).ToList();
            var returnValue = Json(teamDropDownItems);
            return Json(teamDropDownItems);
        }       
    }
}

Club 27/Views/Bookings/Create.cshtml
@model Club_27.Models.Booking

@{
    ViewData["Title"] = "Create";
    var venueListItem = ViewBag.venueDropDown;
    var activityListItem = ViewBag.activityDropDown;
    var teamListItem = ViewBag.teamDropDown;
}

@*<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>*@
@*<script type="text/javascript"src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>*@


<h1>Create</h1>

<h4>Booking</h4>
<hr />

<form method ="post">
  <br />
  
  <br />
        <select asp-for ="ActivityID">
           <option selected>--Activity--</option>
            @foreach (var item in activityListItem)
                    {
                        <option value="@item.ActivityID">@item.ActivityName</option>
                    }
       </select>
       <br />
       <br/>
  <select asp-for ="VenueID">
           <option selected>--Venue--</option>
           @foreach (var item in venueListItem)
                    {
                        <option value="@item.ID">@item.VenueName</option>
                    }
       </select>
    <br />
       <br />
       <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
  </div>
  <br />
     <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
  </div>
  <br />
@*  <div class="form-group">
                <label asp-for="Fixture" class="control-label"></label>
                <input asp-for="Fixture" class="form-control" />
                <span asp-validation-for="Fixture" class="text-danger"></span>
  </div>*@
  <br/>
  @*<div class="form-group">
            <label>Select Participants</label>
            <br/>
            @Html.ListBoxFor(Model => Model.ParticipantList, (IEnumerable<SelectListItem>)teamListItem , new {multiple = "multiple"})
        </div>*@

         <select asp-for="ParticipantList" multiple="multiple">
            @foreach (var item in teamListItem)
                    {
                        <option value="@item.Value">@item.Value</option>
                    }
       </select>
</div>
       <br />
       <br />

       
  @*     @if (ViewBag.ErrorMessage != null)
    {
        <h1>@ViewBag.ErrorMessage</h1>
    }*@
    <button type ="submit" id= "button" class= "btn btn-primary">
       Create
   </button>

   <p style = "color:red;">
           @Html.Label("",Convert.ToString((string)ViewBag.Error))
       </p> 

       <p style = "color:red;">
           @Html.Label("",Convert.ToString((string)ViewBag.OverlimitError))
       </p> 
</form>


@*<select id="sports" style="width:150px;">
    <option value="" selected hidden>-- select</option>
</select>*@

@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeID" class="control-label"></label>
                <input asp-for="EmployeeID" class="form-control" />
                <span asp-validation-for="EmployeeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActivityID" class="control-label"></label>
                <input asp-for="ActivityID" class="form-control" />
                <span asp-validation-for="ActivityID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>*@

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section scripts{
    <script>
        $(function () {       
            $("#multiSelectDropDown").chosen({
                width: "100%"
            });
            
        });
    </script>
}*@

@section scripts{
    <script>
$(document).ready(function(){
  $("#ActivityID").change(function(){
    var selectedIds = $(this).val();
      $.ajax({url: '@Url.Action("GetVenueList" , "Bookings")', type:"post", data:{id:selectedIds} ,success: function(result){
      if(result != null)
      {
          $("#VenueID").empty();
            $.each(result, function (i,value) {
                $("#VenueID").append($("<option></option>").val(value.value).html(value.text));
            });
      }
    }});
  });
});
</script>

<script>
$(document).ready(function(){
  $("#ActivityID").change(function(){
    var selectedIds = $(this).val();
      $.ajax({url: '@Url.Action("GetTeamList" , "Bookings")', type:"post", data:{id:selectedIds} ,success: function(result){
      if(result != null)
      {
          $("#ParticipantList").empty();
            $.each(result, function (i,value) {
                $("#ParticipantList").append($("<option></option>").val(value.value).html(value.text));
            });
      }
    }});
  });
});
</script>

<script>
 $(document).ready(function()
    {
        
        $('#ParticipantList').select2();
    });
</script>
}
@*
@section scripts{
    <script>
$(document).ready(function(){
  $("button").click(function(){
    $.ajax({url: '@Url.Action("Create" , "Enrollments")', type:"post" ,success: function(result){
      if(result != null)
      {
          alert(result.ToString());
      }
    }});
  });
});
</script>
}*@

@*@section scripts{
    <script>
    $(document).ready(function()
    {
        var list=
        [
            "cricket","volleyball"
        ];
        $('#sports').select2({
            data:list
        });
    });
</script>
}*@

@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeID" class="control-label"></label>
                <input asp-for="EmployeeID" class="form-control" />
                <span asp-validation-for="EmployeeID" class="text-danger"></span>

                <select id="EmployeeID" style="width:150px;">
                    <option value="">--select--</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ActivityID" class="control-label"></label>
                <input asp-for="ActivityID" class="form-control" />
                <span asp-validation-for="ActivityID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>*@

Club 27/Views/Bookings/Delete.cshtml
@model Club_27.Models.Booking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Club 27/Views/Bookings/Details.cshtml
@model Club_27.Models.Booking

@{
    ViewData["Title"] = "Details";
    //var obj = ViewBag.GetObj;
}

<h1>Details</h1>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
         <dt class = "col-sm-2">
            ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            Venue ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenueID)
        </dd>
        <dt class = "col-sm-2">
            Activity ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActivityID)
        </dd>
         <dt class = "col-sm-2">
            Start
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
         <dt class = "col-sm-2">
            End
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.End)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Club 27/Views/Bookings/Edit.cshtml
@model Club_27.Models.Booking

@{
    ViewData["Title"] = "Edit";
    var venueListItem = ViewBag.venueDropDown;
    var activityListItem = ViewBag.activityDropDown;
    var teamListItem = ViewBag.teamDropDown;
 }

 <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript"src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<h1>Edit</h1>

<h4>Booking</h4>
<hr />
<form method ="post">
  <br />
   <br />
        <select asp-for ="ActivityID">
           <option selected>--Activity--</option>
            @foreach (var item in activityListItem)
                    {
                        <option value="@item.ActivityID">@item.ActivityName</option>
                    }
       </select>
       <br />
       <br/>
  
 <select asp-for ="VenueID">
           <option selected>--Venue--</option>
           @foreach (var item in venueListItem)
                    {
                        <option value="@item.ID">@item.VenueName</option>
                    }
       </select>
    <br />
    <br />
      <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
  </div>
  <br />
     <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
  </div>
  <br />
  <br/>
       <select asp-for="ParticipantList" multiple="multiple">
            @foreach (var item in teamListItem)
                    {
                        <option value="@item.Value">@item.Value</option>
                    }
       </select>
       <br />
       <br />

   <button type ="submit" class= "btn btn-primary">
       Edit
   </button>

    <p style = "color:red;">
           @Html.Label("",Convert.ToString((string)ViewBag.Error))
       </p> 
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts{
    <script>
$(document).ready(function(){
  $("#ActivityID").change(function(){
    var selectedIds = $(this).val();
      $.ajax({url: '@Url.Action("GetVenueList" , "Bookings")', type:"post", data:{id:selectedIds} ,success: function(result){
      if(result != null)
      {
          $("#VenueID").empty();
            $.each(result, function (i,value) {
                $("#VenueID").append($("<option></option>").val(value.value).html(value.text));
            });
      }
    }});
  });
});
</script>

<script>
 $(document).ready(function()
    {        
        $('#ParticipantList').select2();
    });
</script>
}

Club 27/Views/Bookings/Index.cshtml
@model IEnumerable<Club_27.Models.Booking>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>Booking ID</th>
                <th>Venue</th>
                <th>Activity</th>
                <th>Start</th>
                <th>End</th>
                <th>Fixture</th>
                <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>@item.ID</td>
            <td>@item.Venue.VenueName</td>
            <td>@item.Activity.ActivityName</td>
            <td>@item.Start</td>
            <td>@item.End</td>
            <td>@item.Fixture</td>
            <td>
                <a asp-controller="Bookings" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-controller="Bookings" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>